version: '3.8'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mypet
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: mypet
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
  redis:
    image: redis
    ports:
      - "6379:6379"