name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 'temurin', 'zulu', 'adopt' 등
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy files via SSH to develop
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "build/libs/*"
          target: "/home/ec2-user/develop/"


      - name: Restart server on develop
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            pkill -f 'java -jar'
            nohup java -jar /home/ec2-user/develop/your-app-name.jar &