name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: docker build -t minhyuk0828/mypetdb:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push minhyuk0828/mypetdb:${{ github.sha }}

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Remove existing Docker Compose installation
            sudo rm -f /usr/local/bin/docker-compose
            
            # Install latest Docker Compose
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
            
            # Verify installation
            docker compose version
            
            # Rest of your deployment script...
            # Pull the Docker image
            docker pull minhyuk0828/mypetdb:${{ github.sha }}
            
            # Copy the .env file from GitHub Actions to EC2 instance
            echo "Fetching .env file..."
            scp -i ${{ secrets.KEY }} .env ubuntu@${{ secrets.HOST }}:/home/ubuntu/.env

            # Create docker-compose.yml file
            cat << EOF > docker-compose.yml
            version: '3.8'
            services:
              app:
                image: minhyuk0828/mypetdb:${{ github.sha }}
                ports:
                  - "8080:8080"
                environment:
                  - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mypet
                  - SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}
                  - SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
                  - SPRING_REDIS_HOST=redis
                depends_on:
                  - mysql
                  - redis
            mysql:
              platform: linux/x86_64
              image: mysql:8.0               
              ports:
                - "3307:3306"
               environment:
                - MYSQL_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
                - MYSQL_DATABASE=mypet
              volumes:
                - mysql_data:/var/lib/mysql
            redis:
              image: redis:7.2
              ports:
                - "6379:6379"
              volumes:
                - redis_data:/data
            volumes:
              mysql_data:
              redis_data:
            EOF
            
            # Run Docker Compose
            docker-compose up -d